### ISSUE TITLE
No Ping Response

### ISSUE THREAD

**Issue by Zuendapp** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#11]
Hi,

i have used Remote-Wake-Sleep-On-LAN-Server over two years but since a few weeks the ping says "Still Down" and PC is asleep. The wake succeeds but the response is wrong. A ping from my Pi to PC works. Do you have any idea?

Thank you very much!

Best regards

**Comment by sciguy14** [comment]
Hmm. What OS is the machine that you are waking up? Did you recently upgrade or make any other network changes in the last few weeks?

The Wake-Features depends on the MAC address, but the ping feature depends on the IP. So, if the IP changed, but the NIC remained the same (thus, same MAC) you might see this issue.

**Comment by Zuendapp** [comment]
Hi,
Windows 10. I'have moved my folder from /var/www to a virtual machine with debian OS and it works, but I have the same problem with a second RaspberryPi. I have also changed in config.php the IP Adress to my routers IP which is always on, but the state is also ".... is presently asleep". A normal ping to all of my IP addresses works :(.

Best regards
