### ISSUE TITLE
Get dynamic IP address

### ISSUE THREAD

**Issue by rws-timo** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#17]
Hi,

this tool is working fine but I would like to get the "COMPUTER_LOCAL_IP" via dynamic resolution instead of using a fixed list. Would it be possible to get the dynamic ip address by using "gethostbyname" inside the index.php? As I am not into php, I would be glad if someone could help me with this one.

Best regards,
Timo

**Comment by sciguy14** [comment]
Hi Timo - in my experience, this doesn't work reliably, base on different network topologies. That's why I recommend setting a reserved DHCP address and using that. It's the only thing that works reliably across different network configs.
