### ISSUE TITLE
Support ArchLinuxARM

### ISSUE THREAD

**Issue by z3ntu** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#26]
The only difference is that the executable is called `wol` instead of `wakeonlan`. Maybe both should be tried?

**Comment by sciguy14** [comment]
Would be easy easy enough to implement. If you've done this, please submit it as a pull request.

**Comment by z3ntu** [comment]
No, I have just changed the `wakeonlan` to `wol` 😉

**Comment by sciguy14** [comment]
ok closing this unless you wanna add the try/catch for this and submit it as something that will work for both platforms.
