### ISSUE TITLE
Not Waking 

### ISSUE THREAD

**Issue by screwfaze** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#32]
HYi,

I have installed following your instructions but when I execute the wake up command nothing happens. Can you please help. This is the message i get "FAILED! Server doesn't seem to be waking up... Try again?"

Thanks

**Comment by Rustymage** [comment]
Does WOL work on that pc at all? Have you checked out whether the magic packet is being sent?

**Comment by topcat30** [comment]
I also cant wake or Sleep.
WOL is working from an Android app currently.
