### ISSUE TITLE
Wakeup local computers by using Google Home (and Alexa)

### ISSUE THREAD

**Issue by harolds** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#33]
I have modified the script a bit to make it usable from IFTTT. Now I can say 'Wakeup the server' to my Google Home and it will run this script via IFTTT. The result is that my 'big' server is started and I can watch movies :-)

**Comment by sciguy14** [comment]
That's awesome! If you've done it in a way that doesn't break other functionality, submit it as a pull request :)
