### ISSUE TITLE
Changing the port from port 80

### ISSUE THREAD

**Issue by tuckaluck** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#34]
Sorry if this is in the wrong spot.

Is there any way to change the port from port 80 after installation?

I'm currently running pihole on the RPI as well and would like to keep that on port 80?

**Comment by sciguy14** [comment]
If you follow the https instructions, that will put it on port 443.

Jeremy Blum
Blum Idea Labs, LLC.
http://www.jeremyblum.com

**Comment by tuckaluck** [comment]
Thanks, this should have been obvious. Can I start the installation steps again from the start of the SSL instructions without any issue?

**Comment by sciguy14** [comment]
You should be able to. Give it a shot

Jeremy Blum
Blum Idea Labs, LLC.
http://www.jeremyblum.com

**Comment by cartersm** [comment]
For future travelers: If you want the apache server to listen on a port other than 80, follow [these instructions](https://www.cyberciti.biz/faq/linux-apache2-change-default-port-ipbinding/).
