### ISSUE TITLE
Can't Shut Down Remote Machine

### ISSUE THREAD

**Issue by interfectoren** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#35]
I decided to do this over the weekend and got everything up and running perfectly, however I can't shut down the remote machine through the same website. Immediately after type in the passphrase I get "Command Failed: Connection timed out after 5001 milliseconds." Is there a setting in windows that I might have missed turning on? It will turn on the machine just fine, just not put it back to sleep. That is most of why I liked this project so much, so if there is a fix for it someone please let me know.

**Comment by Rustymage** [comment]
You need a third party app for that. The app listens on a port of your choosing for the shutdown command sent by the program. Use google and type in ‘Sleep one lan’. It’s on Github. 

You may need to configure the text file. Once running on your pc, you can start and stop at will!

Hope this helps.
