### ISSUE TITLE
[Not an issue] - PHP has been update. Affects the tutorial.

### ISSUE THREAD

**Issue by keem85** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#37]
Just noticed that php has been updated, and copy/paste the tutorial will not work. Every place it says "php5", swap it with "php7.0". It also affects the commands further down that points to php5 folder, that also has to be changed to the new location /php/7.0/xxx.

**Comment by cartersm** [comment]
I ran into the same issue; seems that just replacing `php5` by `php` also installs 7.0. Server works fine for me on php7.

**Comment by sciguy14** [comment]
Raspberry Pi latest is now Buster with php 7.3 available from the package manager. I will update the wiki/repo to reflect this soon.

**Comment by sciguy14** [comment]
Wiki has been updated to reflect this change.
