### ISSUE TITLE
Sleep connection refused Ubuntu

### ISSUE THREAD

**Issue by Henrytje** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#40]
Hi there, 

I'm trying to send a sleep command from my Pi to my Ubuntu pc. Waking up works like a charm. However, can't send a sleep command. 

`Going to sleep!
Approved. Sending Sleep Command...

Command failed: Failed to connect to (ip) port 7760: Connection refused`

**Comment by NadirBK** [comment]
It's because for sleep you need a program or a script that turn the computer off

**Comment by Henrytje** [comment]
Thank you for your answer. I'm not that familiar with how to do that, so I will look into it!

**Comment by Henrytje** [comment]
Hmm could someone maybe help me out to update the PHP page to run the script when i'm sending the sleep command?

**Comment by sciguy14** [comment]
Beyond the scope of this application for now.
