### ISSUE TITLE
Created an Docker Image, Please add a Link to the Image/Repo

### ISSUE THREAD

**Issue by ex0nuss** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#43]
Hi sciguy14,

I am using your software for more than a year and I am a huge fan of it.
In the last weeks, I wrote an proper Image with environment variables, documentation and more. 
In the first line of the documentation I gave you credits for the software :)

It would be nice, if you can add a Link in your README / Documentation:
- GitHub: https://github.com/ex0nuss/Remote-Wake-Sleep-On-LAN-Docker
- Dockerhub: https://hub.docker.com/r/ex0nuss/remote-wake-sleep-on-lan-docker

Regards,
ex0nuss

**Comment by sciguy14** [comment]
Done, thanks for making this Docker image! You're timing is great, because I was actually working with Docker for an unrelated project, and was thinking about making a Docker image for this. You'll find a link on the readme, and also on my blog: https://www.jeremyblum.com/2013/07/14/rpi-wol-server/

**Comment by ex0nuss** [comment]
Thx so much for adding it to the Readme and blog! 
The image gets automatically updated on every sunday ^^ 
Just a quick note: The docker image does not run on a Raspberry Pi since it's build for x86.

**Comment by sciguy14** [comment]
Good point, I updated to note to point out that its an x86 Docker image.

**Comment by ex0nuss** [comment]
Perfect! 
If there are any Issues from users regarding docker, forward them to my repo ^^
