### ISSUE TITLE
[SUGGESTION] Setup fails without NAT loopback

### ISSUE THREAD

**Issue by sk1ddy** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#44]
Hi! I am a great fan of your work, I've used it for many years! So with my 2nd new raspberry pi4 I checked out your new beta setup and wanted to try it.
However, It looks like my new home router (I moved into another country) does not support NAT Loopback (probably it could, but it's not configurable by the user). I know, pretty bad router :( 
So, I am pretty sure this is the main reason the setup fails during the accessibility check of the apache server on ports 80 and/or 443 (and even manually skipping that step, it fails in the "Modify WOL Config File" step. The stack trace just returns "http.client.BadStatusLine: UNKNOWN 400 Bad Request". I know that there are some workarounds for such situations, and the best solution would be to just get a Router that actually supports NAT Loopback (I definitely will). I just wanted to inform you about this, so you can decide what you think it's best, whether to implement some sort of workaround, or at least inform the user - with a more meaningful error message - that this is one of the possible reasons the setup failed.

**Comment by sciguy14** [comment]
I will note in the instructions that NAT loopback is required, I don't see a great way around this for now if SSL certs are going to be used.
