### ISSUE TITLE
Can not wake up LAN computers

### ISSUE THREAD

**Issue by briancblog** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#45]
Hello,

Thank you for your great app!

I can wake my lan computers by linux ether-wake program, but that is not a friend GUI for people.

I like your app, but it failed to wake up a lan computer. What is port for wakeup, please? Is there other app or plugin required to make it work?

And could you please all a user/password to this program?

Thank you so much!
Brian

**Comment by sciguy14** [comment]
HI @briancblog please try again with the V3 version and setup instructions on the wiki. It has instructions for how to setup your computer to be waked up. Different computers have the settings configured differently in the UEFI/BIOS.
