### ISSUE TITLE
Website says "Desktop is currently asleep" even though it isn't.

### ISSUE THREAD

**Issue by DwertlePlayz** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#46]
The website shows "desktop is currently asleep" even though it is not. I double-checked and the config file is correct, the port forwarding is done, and the pi is connected to the router through ethernet (so is the pc). Did I miss anything?
![image](https://user-images.githubusercontent.com/72671939/114940859-640a6400-9e10-11eb-8ced-a85fbe01f738.png)

**Comment by DwertlePlayz** [comment]
I'm not too sure if it helps, but the pi is connected to the router directly through ethernet while the computer is connected through an ethernet switch that is connected to the router.

**Comment by mihcox** [comment]
Having the same issue myself, it does work to start the computer but it cannot tell if its online.

Using in docker, with RPi pihole as dhcp.

**Comment by sciguy14** [comment]
This means that ping requests are not being replied. You will need to make sure the computer you are trying to control is configured to allow ICMP ping requests. Many have this _disabled_ by default. See here: https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/wiki/Installation-(v3)#setting-up-the-remote-machines
