### ISSUE TITLE
" Error installing prerequisite software"

### ISSUE THREAD

**Issue by keem85** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#49]
When I am at the script python setup I get "Error installing prerequisite software".  followed by "Script Exiting due to failure in 'Install Prequisite Software' setup step".

Is there a way to remedy this?

Running: Install Prequisite Software
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php7.3-common' for regex 'php7.3'
E: Unable to locate package php7.3-curl
E: Couldn't find any package by glob 'php7.3-curl'
E: Couldn't find any package by regex 'php7.3-curl'
E: Unable to locate package libapache2-mod-php7.3
E: Couldn't find any package by glob 'libapache2-mod-php7.3'
E: Couldn't find any package by regex 'libapache2-mod-php7.3'
Error installing prerequisite software.
Script Exiting due to failure in 'Install Prequisite Software' setup step.

**Comment by muhdzakiy24** [comment]
You will need to edit the setup.py script and change every php7.3 to php7.4.

**Comment by sciguy14** [comment]
This is fixed by #57
