### ISSUE TITLE
No option For hosting the service at localhost

### ISSUE THREAD

**Issue by nikhil631** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#50]
Hello, I have specifically bought a raspberry pi because i needed to make a wake or sleep on lan server, The problem i am facing is that, My router doesn't allow port forwarding and due to this the setup fails after setting ddns.

I wanted to know, Is there any option i can expose the web server to Localhost rather than my public ip, So that I can just use tunneling on localhost rather than port forwarding.

**Comment by sciguy14** [comment]
There isn't much point in using this software if you don't have port forwarding. WOL when already inside the network is easy and doesn't require to forward the magic packet via a raspberry pi. If you aren't planning to do WOL from outside the network then just use something like this to wake up the machine on your local network: https://apps.microsoft.com/store/detail/wake-on-lan/9WZDNCRDFSHB?hl=en-us&gl=us&rtc=1
