### ISSUE TITLE
Getting error on RPI4 

### ISSUE THREAD

**Issue by greenHardik** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#51]
Note, selecting 'php7.3-common' for regex 'php7.3'
Note, selecting 'php7.3-sass' for regex 'php7.3'
Note, selecting 'php-sass' instead of 'php7.3-sass'
E: Unable to locate package php7.3-curl
E: Couldn't find any package by glob 'php7.3-curl'
E: Unable to locate package libapache2-mod-php7.3
E: Couldn't find any package by glob 'libapache2-mod-php7.3'
E: Couldn't find any package by regex 'libapache2-mod-php7.3'
Error installing prerequisite software.
Script Exiting due to failure in 'Install Prequisite Software' setup step.

![image](https://user-images.githubusercontent.com/6195879/172378198-efd20c8f-6112-415e-bbf4-f6731e99e045.png)

**Comment by sciguy14** [comment]
This has been fixed by #57
