### ISSUE TITLE
Invalid Password when use wol shutdown win11 pc

### ISSUE THREAD

**Issue by Nebulosa-Cat** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#61]
![image](https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/assets/30948446/c65f63cf-5093-4189-aa96-373a10327196)

as title, got this problem, and wake on function work normally.

already setting bios and windows firewall but still doesn't work, setting inside config.php is 

```$COMPUTER_SLEEP_CMD = "poweroff";```

(by the way, is there any way add more option like this ? like i need use turn-on、reboot、shutdown...etc)

**Comment by sciguy14** [comment]
Are you using the setup script? The password hash should be generated automatically and put in the config file for you.

The available on/off options are a function of receiving host software: http://www.ireksoftware.com/SleepOnLan/
