### ISSUE TITLE
The wake up procedure is not dynamic when using nginx

### ISSUE THREAD

**Issue by antonovfr** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#62]
Hi,

I am using a bit of a different setup for my WOL web interface.

I run the code in the repo, but I do not use apache. Instead I use Nginx with php-fpm.

My issue is that with this setup, everything work but I do not see the updates in real time.

When I click on wake up the page hangs, and once my PC is up or it exhausted the pings, it loads the page.

Any idea why this happens? I know it's not a supported usage so feel free to close this.

Thanks in advance!

**Comment by sciguy14** [comment]
Sorry, but I'm not sure. If you want to modify this to add support for nginx, feel free to submit a PR with support added.
