### ISSUE TITLE
Install issue related to snapd 

### ISSUE THREAD

**Issue by trojannnn** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#63]
Hi there, 

First of all thanks a lot for creating this, I have used it for multiple years using V1 and V2. However, V2 stopped working and I followed all the instructions in the V3 page: installing Raspberry Pi OS Lite on my raspberry 2. 

During the installation, I get the following error: 

'Job for snapd.service failed because the control process exited with error code'

If I do systemctl status snapd I get the following: 

` systemctl status snapd
● snapd.service - Snap Daemon
     Loaded: loaded (/lib/systemd/system/snapd.service; enabled; vendor preset:>
     Active: failed (Result: exit-code) since Fri 2023-08-04 18:41:15 BST; 5min>
TriggeredBy: ● snapd.socket
    Process: 760 ExecStart=/usr/lib/snapd/snapd (code=exited, status=1/FAILURE)
   Main PID: 760 (code=exited, status=1/FAILURE)
        CPU: 782ms

Aug 04 18:41:15 raspberrypi systemd[1]: snapd.service: Scheduled restart job, r>
Aug 04 18:41:15 raspberrypi systemd[1]: Stopped Snap Daemon.
Aug 04 18:41:15 raspberrypi systemd[1]: snapd.service: Start request repeated t>
Aug 04 18:41:15 raspberrypi systemd[1]: snapd.service: Failed with result 'exit>
Aug 04 18:41:15 raspberrypi systemd[1]: Failed to start Snap Daemon.
Aug 04 18:41:15 raspberrypi systemd[1]: snapd.service: Triggering OnFailure= de>
Aug 04 18:41:15 raspberrypi systemd[1]: snapd.service: Failed to enqueue OnFail>`

And when I try /usr/lib/snapd/snapd I get: 

AppArmor status: apparmor not enabled
2023/08/04 18:53:03.159826 daemon.go:347: started snapd/2.49-1+rpi1+deb11u2 (ser                                                            ies 16; classic; devmode) raspbian/11 (armel) linux/6.1.21.
2023/08/04 18:53:03.459476 daemon.go:440: adjusting startup timeout by 30s (pess                                                            imistic estimate of 30s plus 5s per snap)
cannot run daemon: state startup errors: [cannot obtain snap-seccomp version inf                                                            ormation:
-----
2023/08/04 18:53:03 unknown kernel arch "armv6l"
panic: unknown kernel arch "armv6l"

goroutine 1 [running]:
log.Panicf(0x600e6d, 0x16, 0x2497f48, 0x1, 0x1)
        log/log.go:358 +0x9c
github.com/snapcore/snapd/arch.dpkgArchFromKernelArch(0x24149b6, 0x6, 0x0, 0x249                                                            e51c)
        github.com/snapcore/snapd/arch/arch.go:117 +0x460
github.com/snapcore/snapd/arch.DpkgKernelArchitecture(0x5fb00c, 0x5)
        github.com/snapcore/snapd/arch/arch.go:95 +0x18
main.init()
        github.com/snapcore/snapd/cmd/snap-seccomp/main.go:637 +0x5f0
-----]

Is there any solution for this? 

Keep up the good work!

**Comment by JTricky** [comment]
I have also been using V1 and V2 for years. I tried to install V3 and I had all the same errors on my Raspberry Pi Zero W. I did a bit of research and it seems that the Raspberry Pi Zero W is on the Arm V6. Apparently the snapd in this script will only work with Arm V7 or later. I purchased a Raspberry Pi Zero 2 W and this installed V3 just fine.

**Comment by sciguy14** [comment]
Thanks for weighing in @JTricky - indeed, I wasn't able to get ddclient behavior properly unless it was installed via snap, so you'll need a pit that supports that. Alternatively, just do the DDNS step on your router and avoid ddclient on the Pi.
