### ISSUE TITLE
rc.local stuck

### ISSUE THREAD

**Issue by trojannnn** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#68]
Hi sciguy, 

I have used the raspberry pi with your project on it for many years and I really like it. However, I now get an error after a month of installing it on startup: it is stuck in a rc.local script on startup and I don't seem to get out of it. I used the recommended bullseye version of the raspberry pi and then executed your installation script v3. 

Could you help me please? Thanks in advance!

**Comment by sciguy14** [comment]
what are the errors your are seeing? Where is it "getting stuck"?
