### ISSUE TITLE
"Error installing prerequisite software" (key is stored in legacy trusted.gpg keyring)

### ISSUE THREAD

**Issue by MarcoPo10** [sciguy14/Remote-Wake-Sleep-On-LAN-Server#72]
I've been trying to get this running on a Pi Zero 2W, getting this same error during the setup.py step every time. I've flashed every version of Raspberry Pi OS Lite (bookworm) from March 2024 going back to December 2023 with the same results. Since the default username and password have been removed from the OS since early 2022 I set up the image with username "pi" and password "raspberry" for the install. I don't think that's causing the issue here. I also checked the URL included in the error as well as opening the /etc/apt/trusted.gpg file. The URL was a dead-end and the gpg file was scrambled. 

Error:
_Running: Install Prequisite Software
Hit:1 http://raspbian.raspberrypi.com/raspbian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Reading package lists... Done_                             
**W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
/bin/sh: 1: Syntax error: Unterminated quoted string
Error installing prerequisite software.
Script Exiting due to failure in 'Install Prequisite Software' setup step.**

![Screenshot 2024-05-17 at 4 30 13 PM](https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/assets/69820564/03ca201c-4679-4c4d-8334-6beb5536250e)

![Screenshot 2024-05-17 at 4 41 07 PM](https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/assets/69820564/e5b0d294-2724-458e-aa4b-c64c92780376)

**Comment by lukee12zakk** [comment]
i have the same problem exept a bit different
![image](https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/assets/156796366/99c8e00c-36d8-4053-9686-dcb064668097)

**Comment by JTricky** [comment]
I'm getting the same error as @lukee12zakk except mine is erroring out after reading the package lists of Hit : 4

**Comment by itzmattu** [comment]
Same error as the OP. I'm on a Raspberry Pi 2B, fresh install but setup a user/pass (instructions mention script relies on no password for sudo, but I assume it would just popup a sudo pw prompt.

**Comment by itzmattu** [comment]
I went through the script and fixed what was going wrong with this error.

https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/pull/73

Be advised that this still resulted in a 403 Forbidden error when trying to reach the web server. I simply deleted the symlink created at /var/www and copied the contents of $HOME/RWSOL/www to /var/www instead, and then it worked great.
